/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/yuchen/Desktop/Ros-Python_ws_rv/src/ros_myo/msg/Emg.msg
 *
 */


#ifndef ROS_MYO_RV_MESSAGE_EMG_H
#define ROS_MYO_RV_MESSAGE_EMG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_myo_rv
{
template <class ContainerAllocator>
struct Emg_
{
  typedef Emg_<ContainerAllocator> Type;

  Emg_()
    : data1(0)
    , data2(0)
    , data3(0)
    , data4(0)
    , data5(0)
    , data6(0)
    , data7(0)
    , data8(0)  {
    }
  Emg_(const ContainerAllocator& _alloc)
    : data1(0)
    , data2(0)
    , data3(0)
    , data4(0)
    , data5(0)
    , data6(0)
    , data7(0)
    , data8(0)  {
    }



   typedef int8_t _data1_type;
  _data1_type data1;

   typedef int8_t _data2_type;
  _data2_type data2;

   typedef int8_t _data3_type;
  _data3_type data3;

   typedef int8_t _data4_type;
  _data4_type data4;

   typedef int8_t _data5_type;
  _data5_type data5;

   typedef int8_t _data6_type;
  _data6_type data6;

   typedef int8_t _data7_type;
  _data7_type data7;

   typedef int8_t _data8_type;
  _data8_type data8;




  typedef boost::shared_ptr< ::ros_myo_rv::Emg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_myo_rv::Emg_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Emg_

typedef ::ros_myo_rv::Emg_<std::allocator<void> > Emg;

typedef boost::shared_ptr< ::ros_myo_rv::Emg > EmgPtr;
typedef boost::shared_ptr< ::ros_myo_rv::Emg const> EmgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_myo_rv::Emg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_myo_rv::Emg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_myo_rv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'ros_myo_rv': ['/home/yuchen/Desktop/Ros-Python_ws_rv/src/ros_myo/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_myo_rv::Emg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_myo_rv::Emg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_myo_rv::Emg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_myo_rv::Emg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_myo_rv::Emg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_myo_rv::Emg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_myo_rv::Emg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7f25abeb08e5de082d5895251c79bdd";
  }

  static const char* value(const ::ros_myo_rv::Emg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7f25abeb08e5de0ULL;
  static const uint64_t static_value2 = 0x82d5895251c79bddULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_myo_rv::Emg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_myo_rv/Emg";
  }

  static const char* value(const ::ros_myo_rv::Emg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_myo_rv::Emg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#EmgArray message for the Thalmic Myo, which has 8 EMG sensors \n\
#arranged about the arm\n\
int8 data1\n\
int8 data2\n\
int8 data3\n\
int8 data4\n\
int8 data5\n\
int8 data6\n\
int8 data7\n\
int8 data8\n\
";
  }

  static const char* value(const ::ros_myo_rv::Emg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_myo_rv::Emg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data1);
      stream.next(m.data2);
      stream.next(m.data3);
      stream.next(m.data4);
      stream.next(m.data5);
      stream.next(m.data6);
      stream.next(m.data7);
      stream.next(m.data8);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Emg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_myo_rv::Emg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_myo_rv::Emg_<ContainerAllocator>& v)
  {
    s << indent << "data1: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data1);
    s << indent << "data2: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data2);
    s << indent << "data3: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data3);
    s << indent << "data4: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data4);
    s << indent << "data5: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data5);
    s << indent << "data6: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data6);
    s << indent << "data7: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data7);
    s << indent << "data8: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data8);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MYO_RV_MESSAGE_EMG_H
