/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/yuchen/Desktop/Ros-Python_ws_rv/src/ros_myo/msg/MyoArm.msg
 *
 */


#ifndef ROS_MYO_RV_MESSAGE_MYOARM_H
#define ROS_MYO_RV_MESSAGE_MYOARM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_myo_rv
{
template <class ContainerAllocator>
struct MyoArm_
{
  typedef MyoArm_<ContainerAllocator> Type;

  MyoArm_()
    : arm(0)
    , xdir(0)  {
    }
  MyoArm_(const ContainerAllocator& _alloc)
    : arm(0)
    , xdir(0)  {
    }



   typedef uint8_t _arm_type;
  _arm_type arm;

   typedef uint8_t _xdir_type;
  _xdir_type xdir;




  typedef boost::shared_ptr< ::ros_myo_rv::MyoArm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_myo_rv::MyoArm_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MyoArm_

typedef ::ros_myo_rv::MyoArm_<std::allocator<void> > MyoArm;

typedef boost::shared_ptr< ::ros_myo_rv::MyoArm > MyoArmPtr;
typedef boost::shared_ptr< ::ros_myo_rv::MyoArm const> MyoArmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_myo_rv::MyoArm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_myo_rv::MyoArm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_myo_rv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'ros_myo_rv': ['/home/yuchen/Desktop/Ros-Python_ws_rv/src/ros_myo/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_myo_rv::MyoArm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_myo_rv::MyoArm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_myo_rv::MyoArm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_myo_rv::MyoArm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_myo_rv::MyoArm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_myo_rv::MyoArm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_myo_rv::MyoArm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01e586809ffd60cf3f07c41869248647";
  }

  static const char* value(const ::ros_myo_rv::MyoArm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01e586809ffd60cfULL;
  static const uint64_t static_value2 = 0x3f07c41869248647ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_myo_rv::MyoArm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_myo_rv/MyoArm";
  }

  static const char* value(const ::ros_myo_rv::MyoArm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_myo_rv::MyoArm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Arm message for the Thalmic Myo. Using firmware 1.1.4.2, \n\
#Thalmic Gesture Recognition is possible after sync gesture is performed.\n\
\n\
#arm represents which arm the device is on\n\
#Enumerated: UNKNOWN=0, RIGHT=1, LEFT=2\n\
uint8 arm\n\
#xdir represents the direction of the x-axis\n\
#Enumerated: UNKNOWN=0, X_TOWARD_WRIST=1, X_TOWARD_ELBOW=2\n\
uint8 xdir\n\
";
  }

  static const char* value(const ::ros_myo_rv::MyoArm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_myo_rv::MyoArm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm);
      stream.next(m.xdir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MyoArm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_myo_rv::MyoArm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_myo_rv::MyoArm_<ContainerAllocator>& v)
  {
    s << indent << "arm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.arm);
    s << indent << "xdir: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.xdir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MYO_RV_MESSAGE_MYOARM_H
